/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResponsibleGamingRouteImport } from './routes/responsible-gaming'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlayRouteImport } from './routes/play'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleGamingRoute = ResponsibleGamingRouteImport.update({
  id: '/responsible-gaming',
  path: '/responsible-gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/how-to-play': typeof HowToPlayRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/how-to-play': typeof HowToPlayRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/how-to-play': typeof HowToPlayRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/how-to-play'
    | '/play'
    | '/privacy'
    | '/responsible-gaming'
    | '/terms'
    | '/transparency'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/how-to-play'
    | '/play'
    | '/privacy'
    | '/responsible-gaming'
    | '/terms'
    | '/transparency'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/how-to-play'
    | '/play'
    | '/privacy'
    | '/responsible-gaming'
    | '/terms'
    | '/transparency'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  HowToPlayRoute: typeof HowToPlayRoute
  PlayRoute: typeof PlayRoute
  PrivacyRoute: typeof PrivacyRoute
  ResponsibleGamingRoute: typeof ResponsibleGamingRoute
  TermsRoute: typeof TermsRoute
  TransparencyRoute: typeof TransparencyRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-gaming': {
      id: '/responsible-gaming'
      path: '/responsible-gaming'
      fullPath: '/responsible-gaming'
      preLoaderRoute: typeof ResponsibleGamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  HowToPlayRoute: HowToPlayRoute,
  PlayRoute: PlayRoute,
  PrivacyRoute: PrivacyRoute,
  ResponsibleGamingRoute: ResponsibleGamingRoute,
  TermsRoute: TermsRoute,
  TransparencyRoute: TransparencyRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
